# Generated by Django 5.2 on 2025-04-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='books')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='writers.writer')),
            ],
        ),
    ]
