# Generated by Django 5.2 on 2025-04-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tm', models.CharField(max_length=150)),
                ('username_en', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='writers')),
            ],
        ),
    ]
